import type { AppId, WinApp } from "./types";

export const APPS: Record<AppId, WinApp> = {
  explorer: {
    id: "explorer",
    name: "Explorador de archivos",
    singleton: false,
    defaultW: 820,
    defaultH: 540,
    tile: "medium",
    pinned: true,
    desktop: true,
  },
  "this-pc": {
    id: "this-pc",
    name: "Este equipo",
    singleton: false,
    defaultW: 820,
    defaultH: 540,
    tile: "medium",
    desktop: true,
  },
  edge: {
    id: "edge",
    name: "Microsoft Edge",
    singleton: false,
    defaultW: 900,
    defaultH: 600,
    tile: "wide",
    tileColor: "#0078d7",
    pinned: true,
    desktop: true,
  },
  notepad: {
    id: "notepad",
    name: "Bloc de notas",
    singleton: false,
    defaultW: 560,
    defaultH: 420,
    tile: "medium",
    desktop: true,
  },
  calculator: {
    id: "calculator",
    name: "Calculadora",
    singleton: true,
    defaultW: 320,
    defaultH: 520,
    tile: "medium",
  },
  paint: {
    id: "paint",
    name: "Paint",
    singleton: true,
    defaultW: 840,
    defaultH: 580,
    tile: "medium",
  },
  settings: {
    id: "settings",
    name: "Configuración",
    singleton: true,
    defaultW: 860,
    defaultH: 580,
    tile: "medium",
    tileColor: "#0078d7",
  },
  cmd: {
    id: "cmd",
    name: "Símbolo del sistema",
    singleton: false,
    defaultW: 720,
    defaultH: 440,
    tile: "wide",
  },
  store: {
    id: "store",
    name: "Microsoft Store",
    singleton: true,
    defaultW: 920,
    defaultH: 600,
    tile: "wide",
    tileColor: "#0078d7",
    pinned: true,
  },
  photos: {
    id: "photos",
    name: "Fotos",
    singleton: true,
    defaultW: 840,
    defaultH: 560,
    tile: "large",
    tileColor: "#0078d7",
  },
  mail: {
    id: "mail",
    name: "Correo",
    singleton: true,
    defaultW: 880,
    defaultH: 560,
    tile: "wide",
    tileColor: "#0078d7",
    pinned: true,
  },
  calendar: {
    id: "calendar",
    name: "Calendario",
    singleton: true,
    defaultW: 820,
    defaultH: 560,
    tile: "medium",
    tileColor: "#0078d7",
  },
  sticky: {
    id: "sticky",
    name: "Notas adhesivas",
    singleton: false,
    defaultW: 280,
    defaultH: 260,
    tile: "small",
  },
  minesweeper: {
    id: "minesweeper",
    name: "Buscaminas",
    singleton: true,
    defaultW: 360,
    defaultH: 460,
    tile: "medium",
  },
  recycle: {
    id: "recycle",
    name: "Papelera de reciclaje",
    singleton: true,
    defaultW: 700,
    defaultH: 480,
    tile: "medium",
    desktop: true,
  },
  winver: {
    id: "winver",
    name: "Acerca de Windows",
    singleton: true,
    defaultW: 440,
    defaultH: 380,
    tile: "small",
  },
};

export const START_APPS: AppId[] = [
  "edge",
  "store",
  "mail",
  "calendar",
  "photos",
  "settings",
  "calculator",
  "notepad",
  "paint",
  "explorer",
  "cmd",
  "minesweeper",
  "sticky",
];

export const ALL_APPS_LIST: { letter: string; ids: AppId[] }[] = [
  { letter: "B", ids: ["notepad", "minesweeper"] },
  { letter: "C", ids: ["calculator", "calendar", "settings"] },
  { letter: "E", ids: ["explorer", "edge"] },
  { letter: "F", ids: ["photos"] },
  { letter: "M", ids: ["store", "mail"] },
  { letter: "N", ids: ["sticky"] },
  { letter: "P", ids: ["paint"] },
  { letter: "S", ids: ["cmd"] },
];

export const ACCENTS = [
  "#0078d7",
  "#00b7c3",
  "#038387",
  "#00cc6a",
  "#10893e",
  "#107c10",
  "#ffb900",
  "#ff8c00",
  "#e74856",
  "#e81123",
  "#c239b3",
  "#9a0089",
  "#881798",
  "#744da9",
  "#8764b8",
  "#4c4a48",
  "#525e54",
  "#567c73",
  "#486860",
  "#498205",
];

export const WALLPAPERS = [
  { id: "bloom", name: "Hero" },
  { id: "flow", name: "Flujo" },
  { id: "dusk", name: "Atardecer" },
  { id: "forest", name: "Bosque" },
  { id: "night", name: "Noche" },
  { id: "accent", name: "Color de acento" },
] as const;
